# sam2.yaml
model_path: "sam2_b.pt"
#input_data_path: "test_data/dog.jpg"
#output_data_path: "outputs/sam_2/jpg"

input_data_path : "test_data/COOKIE.mp4"
preprocess_output_path: "outputs/sam_2/preprocess"
output_data_path: "outputs/sam_2/mp4"

#points: null # 注！必须是 [[]] 格式 不能是[] 否则会报错
points: [[2688, 1512]] # 注！必须是 [[]] 格式 不能是[] 否则会报错

bboxes: null # 注 null 表示 None 不允许直接写 None 否则表示 str 类型
labels: null # 注 null 表示 None 不允许直接写 None 否则表示 str 类型
frame_interval: 1 # frame_interval
